# Generated by Django 3.2.23 on 2023-11-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecomponent',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Запись удалена'),
        ),
    ]
