# Generated by Django 3.2.22 on 2023-10-30 16:11

from django.db import migrations, models
import django.utils.timezone
import garpix_user.mixins.models.confirm.code_length_mixin
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
            },
        ),
        migrations.CreateModel(
            name='ReferralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название реферрального пути')),
                ('referral_hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_password_confirm_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Код восстановления пароля')),
                ('is_restore_code_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Код восстановления подтвержден')),
                ('restore_date', models.DateTimeField(null=True, verbose_name='Дата отправки кода восстановления')),
                ('restore_by', models.CharField(choices=[('phone', 'Номер телефона'), ('email', 'Адрес электронной почты')], default='email', max_length=5)),
                ('phone_confirmation_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Код подтверждения номера телефона')),
                ('phone_code_send_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления кода')),
                ('phone_confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date phone was confirmed')),
                ('new_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Новый номер телефона')),
                ('email_confirmation_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения email')),
                ('email_code_send_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления кода')),
                ('email_confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date email was confirmed')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Новый email')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Номер телефона')),
                ('is_phone_confirmed', models.BooleanField(default=False, verbose_name='Номер телефона подтвержден')),
                ('token_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='user token')),
                ('recognized', models.PositiveIntegerField(choices=[(0, 'Не найден'), (1, 'Гость'), (2, 'Зарегистрирован')], default=0, help_text='Обозначает состояние, в котором распознается пользователь.', verbose_name='Тип')),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Системный пользователь',
                'verbose_name_plural': 'Системные пользователи',
            },
            bases=(garpix_user.mixins.models.confirm.code_length_mixin.CodeLengthMixin, models.Model),
        ),
    ]
